const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("zeroLag", {
  getStatus: () => ipcRenderer.invoke("zerolag:get-status"),
  getMemory: () => ipcRenderer.invoke("zerolag:get-memory"),
  restoreDailyMode: () => ipcRenderer.invoke("zerolag:restore-daily-mode"),
  getGameLibrary: () => ipcRenderer.invoke("zerolag:get-game-library"),
  addGame: () => ipcRenderer.invoke("zerolag:add-game"),
  removeGame: (id) => ipcRenderer.invoke("zerolag:remove-game", id),
  launchGame: (id) => ipcRenderer.invoke("zerolag:launch-game", id),
  getNetworkDiagnostics: () => ipcRenderer.invoke("zerolag:get-network-diagnostics"),
  flushDns: () => ipcRenderer.invoke("zerolag:flush-dns"),
  getSupportHandoff: () => ipcRenderer.invoke("zerolag:get-support-handoff"),
  createSupportBundle: () => ipcRenderer.invoke("zerolag:create-support-bundle"),
  revealSupportBundle: () => ipcRenderer.invoke("zerolag:reveal-support-bundle"),
  recordSupportLog: (message, type) => ipcRenderer.invoke("zerolag:record-support-log", { message, type }),
  getAccountStatus: () => ipcRenderer.invoke("zerolag:get-account-status"),
  registerAccount: (input) => ipcRenderer.invoke("zerolag:register-account", input),
  bindAccountMembership: () => ipcRenderer.invoke("zerolag:bind-account-membership"),
  logoutAccount: () => ipcRenderer.invoke("zerolag:logout-account"),
  getAppConfig: () => ipcRenderer.invoke("zerolag:get-app-config"),
  getUpdateStatus: () => ipcRenderer.invoke("zerolag:get-update-status"),
  createOrder: () => ipcRenderer.invoke("zerolag:create-order"),
  getOrderStatus: (orderId) => ipcRenderer.invoke("zerolag:get-order-status", orderId),
  openWebsite: () => ipcRenderer.invoke("zerolag:open-website"),
  openPurchaseUrl: () => ipcRenderer.invoke("zerolag:open-purchase-url"),
  openSupportUrl: () => ipcRenderer.invoke("zerolag:open-support-url"),
  openPaymentUrl: (url) => ipcRenderer.invoke("zerolag:open-payment-url", url),
  openUpdateUrl: (url) => ipcRenderer.invoke("zerolag:open-update-url", url),
  openExternalUrl: (url) => ipcRenderer.invoke("zerolag:open-update-url", url),
  activateLicense: (code) => ipcRenderer.invoke("zerolag:activate-license", code),
  boost: () => ipcRenderer.invoke("zerolag:boost")
});
